import type { Metadata } from "next";
import { SiteHeader } from "../../../components/SiteHeader";
import { SiteFooter } from "../../../components/SiteFooter";
import { createSupabaseServerClient } from "../../../lib/supabase/server";

export const metadata:Metadata={title:"System Health | Hands Gifted Command Center",robots:{index:false,follow:false}};
const checks=[['Integration Connections','integration_connections'],['Integration Audit Log','integration_audit_log'],['HXOS Sync Outbox','hxos_sync_outbox'],['HXOS Sync Receipts','hxos_sync_receipts'],['Module Status','household_module_status'],['Project Context','project_context_entries'],['Registration Requests','registration_requests'],['Family Access Requests','family_access_requests']];
export default async function SystemHealthPage(){
 let state:"config"|"signed_out"|"denied"|"ready"="signed_out";let counts:Record<string,number>={};
 try{const supabase=await createSupabaseServerClient();const {data:auth}=await supabase.auth.getUser();if(!auth.user)state="signed_out";else{const {data:memberships}=await supabase.from("organization_members").select("organization_id,role").eq("user_id",auth.user.id);const m=memberships?.find(r=>["owner","admin","staff"].includes(String(r.role)));if(!m)state="denied";else{state="ready";const rs=await Promise.all(checks.map(async([,t])=>{const {count}=await supabase.from(t).select("*",{count:"exact",head:true}).eq("organization_id",m.organization_id);return[t,count??0] as const;}));counts=Object.fromEntries(rs);}}}catch{state="config"}
 return <main><SiteHeader/><section className="inner-hero"><span>Reality C.H.E.X.</span><h1>System Health</h1><p>Verify connected systems, synchronization records, module state, requests, and durable project context. This screen reports what the database exposes; it does not label a feature WORKING unless the full write → database → readback → deployment path is verified.</p></section><section className="section">{state!=="ready"?<div className="access-note"><strong>{state==="signed_out"?"AUTH REQUIRED":state==="denied"?"ACCESS DENIED":"PARTIAL — Supabase runtime unavailable"}</strong></div>:<><div className="detail-grid">{checks.map(([label,t])=><article key={t}><span>{label}</span><h3>{counts[t]??0}</h3><p>Durable records currently visible for this verification area.</p></article>)}</div><div className="access-note" style={{marginTop:32}}><strong>Verification standard</strong><p>DATABASE INTEGRITY → AUTH → DATA WRITES → DATA READBACK → COMMAND CENTER → DEPLOYMENT → UI verification. Screens that only read counts remain PARTIAL until their action workflows are tested end to end.</p></div></>}</section><SiteFooter/></main>
}
