import { notFound } from "next/navigation";
import { SiteHeader } from "../../../components/SiteHeader";
import { SiteFooter } from "../../../components/SiteFooter";
import { getPublicResourceArea, publicResourceAreas } from "../../../lib/publicResources";
const topicSlug=(s:string)=>s.toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const art:Record<string,string>={"kids-learning":"/catalog/kids-learning.jpg","food-wellness":"/catalog/cooking.jpg","practical-life-skills":"/catalog/sewing.jpg","household-management":"/hero-family.jpg","family-stability":"/hero-family.jpg","community-resources":"/hero-family.jpg"};
const icons=["✦","⌁","◇","○","△","＋"];
export function generateStaticParams(){return publicResourceAreas.map(a=>({slug:a.slug}));}
export default async function ResourceAreaPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const area=getPublicResourceArea(slug);if(!area)notFound();return <main className="public-page visual-resource-page"><SiteHeader/>
<section className="learning-hero"><div className="learning-hero-copy"><span>{area.tag}</span><h1>{area.title}</h1><p>{area.summary}</p><a className="button gold" href="#explore">Explore the subjects</a></div><div className="learning-hero-art"><img src={art[area.slug]||"/hero-family.jpg"} alt="Hands Gifted family learning"/></div></section>
<section id="explore" className="visual-choice-section"><div className="visual-choice-heading"><span>Choose your path</span><h2>What would you like to explore?</h2><p>Choose one subject. Each opens its own focused Hands Gifted page instead of adding another long section here.</p></div><div className="visual-card-grid">{area.topics.map(([title,body],i)=><a className="visual-topic-card" href={`/resources/${area.slug}/${topicSlug(title)}`} key={title}><div className="visual-topic-icon" aria-hidden="true">{icons[i%icons.length]}</div><div><h2>{title}</h2><p>{body}</p><strong>Explore →</strong></div></a>)}</div></section>
<section className="learning-feature-band"><div><span>Family-guided learning</span><h2>Learn it. Practice it. Use it in real life.</h2><p>{area.childFocus} {area.familyFocus}</p></div><a className="button gold" href="/activities">Try a family activity</a></section>
<section className="faith-thread"><span>Faith throughout Hands Gifted</span><h2>Biblical principles belong in the learning itself.</h2><p>Wisdom, diligence, stewardship, responsibility, service, family care, and developing useful gifts are connected to the subjects where they naturally apply. Deeper scripture references remain available inside each subject page.</p></section>
<SiteFooter/></main>}