import { SiteHeader } from "../components/SiteHeader";
import { SiteFooter } from "../components/SiteFooter";
const doors=[
["Children & Learning","School support, creativity, technology, money skills, discovering gifts, and opportunities for children and youth.","/resources/kids-learning","Learn • Explore • Discover"],
["Family & Home","Routines, meals, household organization, family scheduling, stability, and practical support for parents and caregivers.","/resources/household-management","Plan • Organize • Strengthen"],
["Life Skills","Cooking, gardening, braiding, sewing, creative skills, technology, responsibility, and entrepreneurship.","/skills","Practice • Build • Create"],
["Bible & Faith","Scripture study connected to wisdom, character, family responsibility, work, stewardship, and everyday application.","/resources/kids-learning#scripture","Study • Apply • Grow"],
["Community Resources","Verified assistance, youth programs, workforce opportunities, family resources, and community navigation.","/resources/community-resources","Find Help • Find Opportunity"],
["Shop & Services","Hands Gifted services and original products as they become genuinely ready for customers and families.","/shop","Products • Services • In Development"],
] as const;
const starts=[["Do something together","Choose a guided family activity with supplies, steps, adult guidance, discussion, and faith connection.","/activities"],["Learn a practical skill","Enter Cooking, Gardening, Braiding, or Sewing and build useful ability through practice.","/skills"],["Find family support","Start with household, food, stability, or community-resource information.","/resources"],["Enter the Family Academy","Use the protected learning area for household-specific learning and records.","/academy"]] as const;
export default function Home(){return <main className="hg-home"><SiteHeader/>
<section className="hg-hero simplified-hero"><div className="hg-hero-copy"><div className="hg-kicker">Children • Family • Faith • Skills</div><h1>Discover the gift.<br/><span>Build the skill. Prepare for life.</span></h1><p className="hg-hero-lead">Hands Gifted helps children and families learn, develop practical skills, apply biblical principles to daily life, and find useful resources and opportunities.</p><div className="hg-hero-actions"><a className="button gold" href="#start">Choose where to start</a><a className="button glass" href="/activities">Try an activity</a></div></div><div className="hg-hero-visual"><div className="hg-visual-main"><img src="/catalog/family-learning.jpg" alt="Family learning together"/></div></div></section>
<section id="start" className="hg-section consolidated-section"><div className="hg-section-heading"><span>What do you need today?</span><h2>Choose one clear path.</h2><p>You do not need to understand the whole Hands Gifted system first. Start with the area that matches your family&apos;s need.</p></div><div className="gateway-grid">{doors.map(([t,b,h,k])=><a className="gateway-card" href={h} key={t}><small>{k}</small><h3>{t}</h3><p>{b}</p><strong>Open this area →</strong></a>)}</div></section>
<section className="hg-section quick-start"><div className="hg-section-heading"><span>Start doing, not just reading</span><h2>Four useful next steps.</h2></div><div className="quick-grid">{starts.map(([t,b,h])=><a className="quick-card" href={h} key={t}><h3>{t}</h3><p>{b}</p><strong>Continue →</strong></a>)}</div></section>
<section className="belief-strip"><div><span>Hands Gifted foundation</span><h2>Faith belongs in daily life.</h2><p>Our learning connects biblical principles with preparation, stewardship, diligent work, family responsibility, wisdom, service, and developing the gifts placed in our hands. Scripture is studied in context and applied through real family life.</p></div><a className="button gold" href="/resources/kids-learning#scripture">Explore Bible & Faith</a></section>
<section className="hg-section public-private"><div className="hg-section-heading"><span>One site, clear boundaries</span><h2>Public help stays simple. Private family information stays protected.</h2><p>The public website contains approved learning, activities, resources, services, and products. Child-specific records, assignments, household administration, assessments, and other private family information belong only in protected systems.</p></div><div className="hg-hero-actions"><a className="button gold" href="/resources">Browse public resources</a><a className="button" href="/academy">Family Academy / Login</a></div></section>
<SiteFooter/></main>}