import type { Metadata } from "next";
import Link from "next/link";
import styles from "../dashboard/dashboard.module.css";

export const metadata: Metadata={title:"Executive Dashboard Preview | Hands Gifted",robots:{index:false,follow:false}};

const modules=[
  ["📖","Spiritual Foundation","Bible · Prayer · Sabbath · Study"],
  ["🏠","Wife / Mother & Household","Home · Meals · Routines · Family care"],
  ["💼","Executive / EAA","Schedule · Emails · Tasks · Follow-ups"],
  ["♛","Hands Gifted CEO","Projects · Programs · Content · Business"],
  ["🛡","Family Stability","Housing · Utilities · Transportation · Needs"],
  ["🎓","Family Academy","Learning · Assignments · Progress · Skills"],
  ["🎒","Children & School","Schedules · Assignments · Events · Supplies"],
  ["🍴","Food & Kitchen","Meals · Prep · Inventory · Grocery systems"],
  ["🧹","Home Management","Cleaning · Laundry · Repairs · Organization"],
  ["📦","Inventory Center","Needs · Low items · Household supplies"],
  ["✉","Communication Hub","Email · Messages · Alerts · Follow-ups"],
  ["🖥","Website Development","Content · Design · Pages · Deployment"],
] as const;

export default function DashboardPreview(){
  return <div className={styles.dash}>
    <header className={styles.topbar}><div className={styles.brand}><div className={styles.crown}>♛</div><div className={styles.brandCopy}><strong>HANDS GIFTED</strong><span>Command Center · Dashboard</span></div></div><div className={styles.search}>⌕ <span>Search the Command Center…</span></div><div className={styles.profile}><div className={styles.profileDot}>S</div><div className={styles.profileText}><strong>Shayla</strong><span>Executive Dashboard</span></div></div></header>
    <div className={styles.layout}>
      <aside className={styles.sidebar}><div className={styles.navLabel}>Command</div><a className={`${styles.navLink} ${styles.navActive}`} href="#top"><span className={styles.navIcon}>⌂</span>Dashboard</a><a className={styles.navLink} href="#attention"><span className={styles.navIcon}>☀</span>My Day</a><a className={styles.navLink} href="#schedule"><span className={styles.navIcon}>□</span>Calendar</a><a className={styles.navLink} href="#email"><span className={styles.navIcon}>✉</span>Inbox</a><a className={styles.navLink} href="#modules"><span className={styles.navIcon}>▣</span>Projects</a><a className={styles.navLink} href="#family"><span className={styles.navIcon}>⌂</span>Family</a><a className={styles.navLink} href="#website"><span className={styles.navIcon}>◎</span>Website</a><a className={styles.navLink} href="#modules"><span className={styles.navIcon}>◇</span>Academy</a><div className={styles.sidebarQuote}><strong>Purpose Builds Stronger Families</strong><p>Private software preview · synthetic records only.</p></div></aside>
      <main id="top" className={styles.main}>
        <section className={styles.welcome}><div className={styles.welcomeMain}><h1>Welcome back, Shayla.</h1><p>A one-page executive view of business, website, family, household, learning, messages and next actions.</p></div><div className={styles.affirmation}><span>DESIGN PREVIEW</span><p>Dashboard = awareness. Command Center = action. Website = public experience.</p></div></section>
        <section id="attention" className={styles.attention}><div className={styles.sectionHead}><div className={styles.sectionTitle}><strong>♛ What Needs My Attention</strong><span>Priority work and decisions appear here first.</span></div><a className={styles.sectionLink} href="#modules">View all tasks →</a></div><div className={styles.priorityGrid}><article className={`${styles.priorityCard} ${styles.priorityHigh}`}><div className={styles.priorityLabel}>High priority</div><h3>Website approval needed</h3><p>Developer is waiting on one design decision.</p><a href="#website">Review →</a></article><article className={`${styles.priorityCard} ${styles.priorityMed}`}><div className={styles.priorityLabel}>Medium priority</div><h3>Household follow-up</h3><p>One responsibility needs parent verification.</p><a href="#family">Verify →</a></article><article className={`${styles.priorityCard} ${styles.priorityLow}`}><div className={styles.priorityLabel}>Watch</div><h3>External response pending</h3><p>Follow-up date has been reached.</p><a href="#email">Open →</a></article><article className={styles.captureCard}><div className={styles.captureTop}><div className={styles.capturePlus}>＋</div><div><strong>Quick Capture</strong><br/><span>Add a task, note, idea or reminder.</span></div></div><a href="#quick">Add now</a></article></div></section>
        <section id="modules" className={styles.moduleGrid}>{modules.map(([icon,title,summary])=><a key={title} className={styles.module} href={`#${title.toLowerCase().replaceAll(" ","-")}`}><div className={styles.moduleIcon}>{icon}</div><strong>{title}</strong><span>{summary}</span></a>)}</section>
        <section className={styles.widgets}><article className={styles.widget}><div className={styles.widgetHead}><strong>★ Today’s Priorities</strong><a href="#">View all</a></div>{["Complete top business task","Review one family need","Confirm website next step","Handle one follow-up","Close one loose end"].map((x,i)=><div className={styles.listRow} key={x}><i className={i<2?styles.dot:styles.mutedDot}></i><span>{x}</span><time>{i<2?"Today":"Next"}</time></div>)}</article><article id="schedule" className={styles.widget}><div className={styles.widgetHead}><strong>□ Today’s Schedule</strong><a href="#">Calendar</a></div>{[["6:00 AM","Morning routine"],["8:00 AM","School / work"],["3:30 PM","After-school reset"],["5:30 PM","Family time"],["7:30 PM","Quiet time / study"]].map(([time,title])=><div className={styles.listRow} key={time}><i className={styles.dot}></i><span>{title}</span><time>{time}</time></div>)}</article><article id="email" className={styles.widget}><div className={styles.widgetHead}><strong>✉ Important Emails</strong><a href="#">View all</a></div>{["Project update","Meeting follow-up","Schedule change","New assignment"].map((x,i)=><div className={styles.listRow} key={x}><i className={i===0?styles.dot:styles.mutedDot}></i><span>{x}</span><time>{i===0?"8:45 AM":"Recent"}</time></div>)}</article><article id="website" className={styles.widget}><div className={styles.widgetHead}><strong>◎ Website / Developer</strong><a href="#">Open</a></div><div className={styles.listRow}><i className={styles.dot}></i><span>Preview deployment</span><time>Ready</time></div><div className={styles.listRow}><i className={styles.dot}></i><span>Changes awaiting review</span><time>2</time></div><div className={styles.listRow}><i className={styles.mutedDot}></i><span>Public inquiries</span><time>3</time></div><div className={styles.empty}>Website signals route into Command Center; only action-worthy items surface here.</div></article></section>
        <section id="family" className={styles.statusGrid}><article className={styles.statusPanel}><h3>⌂ Household Status</h3><div className={styles.statusChips}><div className={styles.statusChip}><strong>On track</strong><span>Meals</span></div><div className={styles.statusChip}><strong>On track</strong><span>Chores</span></div><div className={styles.statusChip}><strong>2</strong><span>Low items</span></div><div className={styles.statusChip}><strong>1</strong><span>Review</span></div></div></article><article id="quick" className={styles.statusPanel}><h3>⚡ Quick Actions</h3><div className={styles.quickGrid}><a className={styles.quick} href="#">Add Task</a><a className={styles.quick} href="#">Add Meal</a><a className={styles.quick} href="#">Add Project</a><a className={styles.quick} href="#">Add Supply</a><a className={styles.quick} href="#">Add Note</a><a className={styles.quick} href="#">Add Follow-up</a></div></article><article className={styles.statusPanel}><h3>♟ Family Members</h3><div className={styles.memberRow}>{["Founder","Partner","Child 1","Child 2","Child 3","Child 4","Child 5"].map((name,i)=><div className={styles.member} key={name}><div className={styles.avatar}>{i===0?"S":i===1?"B":String(i)}</div><strong>{name}</strong><span>{i<2?"Adult":"Family"}</span></div>)}</div></article></section>
      </main>
    </div>
    <nav className={styles.mobileNav}><a href="#top"><b>⌂</b><span>Dashboard</span></a><a href="#attention"><b>☀</b><span>My Day</span></a><a href="#quick"><b>＋</b><span>Capture</span></a><a href="#schedule"><b>□</b><span>Calendar</span></a><a href="#modules"><b>☰</b><span>More</span></a></nav>
  </div>;
}
