export type ExploreItem = {
  slug: string;
  title: string;
  tag: string;
  summary: string;
  image: string;
  status: string;
  intro: string;
  highlights: string[];
};

export const exploreItems: ExploreItem[] = [
  {slug:"cooking-food",title:"Hands Gifted Cooking",tag:"Hands Gifted Skill World",summary:"Family cooking, kitchen learning, recipes, stewardship, service development, and future cooking products.",image:"/catalog/cooking.jpg",status:"Service world",intro:"Hands Gifted Cooking is part of the public skill-and-service system. Free learning can cover practical kitchen foundations while complete original products and specific direct services stay in their proper paid or inquiry layers. Prepared-food offers are only presented when applicable safety and legal requirements are confirmed.",highlights:["Free family cooking and kitchen learning","Children building practical kitchen skills","Service inquiries evaluated by readiness","Original recipe books, planners, and future products"]},
  {slug:"gardening",title:"Hands Gifted Gardening",tag:"Hands Gifted Skill World",summary:"Food growing, nature, family science, stewardship, service development, and future garden resources.",image:"/catalog/gardening.jpg",status:"Service world",intro:"Hands Gifted Gardening is a public skill-and-service world. It connects beginner learning, children and family participation, real practice, future service formats, and original garden resources without representing advanced landscaping or horticultural expertise that has not been established.",highlights:["Seeds, containers, plant care, and observation","Children's garden science and stewardship","Service formats developed from demonstrated practice","Garden journals, guides, and future learning products"]},
  {slug:"braiding",title:"Hands Gifted Braiding",tag:"Hands Gifted Skill World",summary:"Natural-hair care, protective styling, creativity, family hair routines, direct appointments, and future hair resources.",image:"/catalog/braiding.jpg",status:"Appointments by inquiry",intro:"Hands Gifted Braiding is the clearest current direct-service lane. Visitors can request an appointment or ask about a style, while exact pricing, timing, preparation, deposit terms, and availability are confirmed before booking is finalized.",highlights:["Natural-hair and braiding inquiries","Protective styling within demonstrated skill","Children's and family hair routines","Future hair-care guides and learning resources"]},
  {slug:"sewing-making",title:"Hands Gifted Sewing",tag:"Hands Gifted Skill World",summary:"Beginner sewing, repair, customization, modest design, family learning, selected service inquiries, and future products.",image:"/catalog/sewing.jpg",status:"Selected work by inquiry",intro:"Hands Gifted Sewing belongs in the public skill-and-service system, but the exact offer must match demonstrated capability. Selected basic repair or customization may be considered by inquiry; full garment construction is not represented as currently available until that skill is established.",highlights:["Basic sewing, repair, and clothing care","Selected customization within demonstrated skill","Children's making and measurement learning","Hands Gifted Sewing Book and future products"]},
  {slug:"art-creativity",title:"Art & Creativity",tag:"Development Lane",summary:"Drawing, painting, character ideas, music, video, design, and family projects used for skill development.",image:"/catalog/art.jpg",status:"In development",intro:"Creative work gives children and families room to explore gifts, practice skills, build portfolios, and connect creativity to technology, learning, and future opportunity. It is a development lane rather than a direct Hands Gifted service world at this stage.",highlights:["Drawing and painting","Character and design concepts","Music and video projects","Parent-approved portfolio pieces"]},
  {slug:"family-learning",title:"Family Learning",tag:"Family Development",summary:"Faith, academics, practical life skills, technology, and parent-guided projects for child and family development.",image:"/catalog/family-learning.jpg",status:"Public resources + protected family practice",intro:"Family learning combines academics, faith, practical skills, creativity, technology, responsibility, and opportunity. Public resources can be shared while private child records and parent-controlled progress remain protected.",highlights:["Bible and Scripture study","Reading, science, and practical life skills","Technology and digital creativity","Explore → learn → practice → create → document"]},
  {slug:"academy",title:"Family Academy",tag:"Protected Family Learning",summary:"Parent-guided learning paths for children and family development with private progress and public-safe explanations.",image:"/catalog/academy.jpg",status:"Protected household-first system",intro:"The Family Academy connects lessons, projects, progress, and parent review inside protected family spaces. Public explanations and selected learning resources can support the wider Hands Gifted mission without publishing private child records.",highlights:["Parent-guided learning","Practical and academic skills","Creative projects","Private progress and parent approval"]},
  {slug:"resources-products",title:"Resources & Products",tag:"Free + Paid Depth",summary:"Public information, original workbooks, books, planners, kits, products, and deeper Hands Gifted tools separated by readiness.",image:"/catalog/resources-products.jpg",status:"Growing product system",intro:"Hands Gifted can provide useful public resources while protecting complete original creations. Products become available only when pricing, delivery, customer support, and any relevant safety or legal requirements are ready.",highlights:["Free public learning and resource navigation","Original books, workbooks, and planners","Skill-based products from Cooking, Gardening, Braiding, and Sewing","Family systems and member resources when ready"]}
];

export function getExploreItem(slug: string){return exploreItems.find((item)=>item.slug===slug);}
