export type ExploreItem = {
  slug: string;
  title: string;
  tag: string;
  summary: string;
  image: string;
  status: string;
  intro: string;
  highlights: string[];
};

export const exploreItems: ExploreItem[] = [
  {slug:"cooking-food",title:"Cooking & Food",tag:"Lived practice + internal R&D",summary:"Real family meals, budget grocery planning, recipes, healthier eating, and hands-on cooking being practiced and documented now.",image:"/catalog/cooking.jpg",status:"LIVED / DOING",intro:"Cooking is one of the clearest real-life Hands Gifted proof areas. Family meals, shopping decisions, recipes, food planning, healthier-eating changes, and kitchen learning are already happening. Future cookbooks, classes, Holy Day resources, or other offers remain possibilities rather than current claims.",highlights:["Family meals and recipe development","Budget grocery planning and household food systems","Cooking with children and practical kitchen learning","Future cookbook, Holy Day, content, and class possibilities"]},
  {slug:"gardening",title:"Gardening",tag:"Exploratory / optional",summary:"A possible future family learning lane for food, nature, science, stewardship, and low-cost gardening projects.",image:"/catalog/gardening.jpg",status:"EXPLORATORY",intro:"Gardening remains optional. It fits the Hands Gifted vision, but it does not need to become an active project until the household has the interest, time, supplies, and capacity to practice it consistently.",highlights:["Possible container gardening and seed starting","Family science and nature learning","Possible low-cost garden kits later","Can remain parked without slowing the larger vision"]},
  {slug:"braiding",title:"Hair & Braiding",tag:"Lived skill",summary:"Natural hair care and braiding are real skills already being practiced inside the household and documented as proof of work.",image:"/catalog/braiding.jpg",status:"LIVED / DOING",intro:"Braiding is not merely a ChatGPT idea. It is an actual practiced skill. Hands Gifted can document approved finished work, learning, maintenance, and portfolio evidence while deciding later whether the skill should remain household self-care, become content, or develop into a service or teaching lane.",highlights:["Household hair maintenance","Protective-style practice","Finished-work portfolio development","Future service or teaching only after readiness"]},
  {slug:"sewing-making",title:"Sewing & Making",tag:"Beginner learning",summary:"Early sewing practice includes fringe and blue-border work and beginner alteration experience; full garment construction is still a learning goal.",image:"/catalog/sewing.jpg",status:"LEARNING",intro:"Sewing is a developing skill, not a mature apparel operation. Current proof includes simple fringe and blue-border work plus beginner garment alteration. Future goals include cleaner construction, skirts, dresses, headwraps, aprons, household textiles, and eventually products or instruction if skill and quality mature.",highlights:["Blue-border and fringe work","Beginner clothing alteration","Future skirts, dresses, headwraps, aprons, and home textiles","Learn → practice → make → evaluate before selling"]},
  {slug:"art-creativity",title:"Art & Creativity",tag:"Supporting development",summary:"Drawing, media, music, design, and family creative projects can support learning, content, and skill discovery without becoming separate businesses now.",image:"/catalog/art.jpg",status:"SUPPORTING",intro:"Creative work supports Hands Gifted by helping the family explore gifts, document learning, create media, and develop useful skills. It does not need to become a separate business lane to have value.",highlights:["Drawing and visual creativity","Music and video projects","Design and content development","Parent-approved portfolio work"]},
  {slug:"family-learning",title:"Family Learning",tag:"Lived practice + framework",summary:"Faith, school support, practical life skills, technology, and parent-guided projects are already part of family life while a broader learning framework is still being developed.",image:"/catalog/family-learning.jpg",status:"LIVED / DEVELOPING",intro:"Family learning combines real parenting and school support with a developing framework for practical skills, creativity, faith, responsibility, and individual gifts. The lived family work is real; a public program or academy is not yet being claimed.",highlights:["Bible and Scripture study","School support and practical life skills","Technology and digital creativity","Private family learning before public programming"]},
  {slug:"academy",title:"Daughters of Sarah / Family Academy",tag:"Chat-developed framework",summary:"A faith-centered learning framework for women, girls, boys, and family development that remains in development rather than a launched public academy.",image:"/catalog/academy.jpg",status:"FRAMEWORK IN DEVELOPMENT",intro:"Daughters of Sarah, Kings of God, and the Family Academy are structured ideas being developed from faith, parenting, household learning, and practical-skills goals. They may guide private family learning now, but they are not presented as mature public institutions or classes.",highlights:["Biblical womanhood and character development","Mother-daughter and family learning","Practical skills and household stewardship","Future public resources only from approved, mature material"]},
  {slug:"resources-products",title:"Resources & Products",tag:"Future roadmap",summary:"Workbooks, journals, recipes, modest apparel, headwraps, household goods, kits, classes, and other products remain future possibilities until they are built and tested.",image:"/catalog/resources-products.jpg",status:"FUTURE",intro:"Future products stay visible so the larger vision is not lost, but they are not treated as current inventory or launched offers. Each item must earn readiness through skill, quality, cost, demand, safety, capacity, and business testing.",highlights:["Future digital workbooks and guides","Future recipe and Holy Day resources","Future modest apparel, headwraps, aprons, and home goods","Future kits, workshops, classes, and events"]}
];

export function getExploreItem(slug: string){return exploreItems.find((item)=>item.slug===slug);}
