export type ExploreItem = {
  slug: string;
  title: string;
  tag: string;
  summary: string;
  image: string;
  status: string;
  intro: string;
  highlights: string[];
};

export const exploreItems: ExploreItem[] = [
  {slug:"cooking-food",title:"Cooking & Food",tag:"Internal R&D",summary:"Family meals, recipes, healthier eating, and hands-on cooking practice being documented as household-tested research.",image:"/catalog/cooking.jpg",status:"Internal R&D",intro:"Cooking remains an internal research-and-development lane during the current 90-day business focus. Hands Gifted documents meals, recipes, skills, and lessons as they are actually practiced without presenting food service as a current public offer.",highlights:["Family meals and recipe development","Cooking 101 with children","Healthier-eating learning","Meal photos, short videos, and future food-service research"]},
  {slug:"gardening",title:"Gardening",tag:"Internal R&D",summary:"Grow food, learn nature, and document household gardening as practical-life research.",image:"/catalog/gardening.jpg",status:"Internal R&D",intro:"Gardening connects family time, science, food, stewardship, and hands-on learning. It remains an internal R&D lane while planting, growth, harvests, and lessons are documented.",highlights:["Container gardening and seed starting","Garden outings and vegetable picking","Plant-growth observations","Harvest-to-kitchen stories"]},
  {slug:"braiding",title:"Hair & Braiding",tag:"Internal R&D",summary:"Household hair care, protective styling, and portfolio development remain internal R&D during the current flagship focus.",image:"/catalog/braiding.jpg",status:"Internal R&D",intro:"Hair and braiding are skill-development and household self-care work during the current 90-day focus. Hands Gifted may document approved proof-of-skill, but this lane is not being presented as a separate active public service at this stage.",highlights:["Household hair maintenance","Protective-style practice","Parent-approved portfolio development","Future service-readiness research"]},
  {slug:"sewing-making",title:"Sewing & Making",tag:"Internal R&D",summary:"Repair, design, sew, and create useful or modest items while building proof of skill.",image:"/catalog/sewing.jpg",status:"Internal R&D",intro:"Sewing and making begin with practical family needs and proof of skill. This lane remains internal R&D unless evidence later supports promotion to an active offer.",highlights:["Basic sewing and repair","Modest apparel ideas","Blue-border fringe proof-of-work","Design → make → photograph → evaluate"]},
  {slug:"art-creativity",title:"Art & Creativity",tag:"Internal R&D",summary:"Drawing, painting, character ideas, music, video, design, and family projects used for skill development.",image:"/catalog/art.jpg",status:"Internal R&D",intro:"Creative work gives the family room to explore gifts, practice skills, and build a private or parent-approved portfolio. It is supporting R&D rather than a competing active business lane.",highlights:["Drawing and painting","Character and design concepts","Music and video projects","Parent-approved portfolio pieces"]},
  {slug:"family-learning",title:"Family Learning",tag:"Internal R&D",summary:"Faith, academics, practical life skills, technology, and parent-guided projects tested inside the household.",image:"/catalog/family-learning.jpg",status:"Internal R&D",intro:"Family learning combines academics, faith, practical skills, creativity, and responsibility into parent-guided activities and projects. It remains internal R&D during the current business focus.",highlights:["Bible and Scripture study","Reading, science, and practical life skills","Technology and digital creativity","Explore → learn → practice → create → document"]},
  {slug:"academy",title:"Family Academy",tag:"Internal R&D",summary:"Parent-guided learning paths for children and family development remain a protected household-first prototype.",image:"/catalog/academy.jpg",status:"Internal R&D",intro:"The Family Academy is a protected household-first learning prototype. It connects lessons, projects, progress, and parent review without publishing private family records and does not compete with the current flagship business offer.",highlights:["Parent-guided learning","Practical and academic skills","Creative projects","Private progress and parent approval"]},
  {slug:"resources-products",title:"Resources & Products",tag:"Future Roadmap",summary:"Additional workbooks, journals, recipes, apparel concepts, and unrelated product lines remain future roadmap unless validated for promotion.",image:"/catalog/resources-products.jpg",status:"Future Roadmap",intro:"Additional resources and product lines stay in the future roadmap until the current Family Household Operating System is validated and a later expansion decision is made.",highlights:["Future family learning resources","Future recipes and garden journals","Future modest-apparel concepts","Future digital workbooks and guides"]}
];

export function getExploreItem(slug: string){return exploreItems.find((item)=>item.slug===slug);}
