export const publicResourceAreas = [
  {
    slug: "kids-learning",
    title: "Children & Learning",
    shortTitle: "Kids & Learning",
    tag: "Learn • Explore • Discover",
    summary: "Educational support, creativity, technology, financial literacy, opportunities, and resources that help children build knowledge and discover their gifts.",
    childFocus: "Give children clear pathways to learn, explore interests, practice useful skills, and prepare for a changing world.",
    familyFocus: "Help parents and caregivers find trustworthy tools, programs, learning ideas, and ways to support each child without exposing private school records.",
    topics: [
      ["School Support", "Reading, math, study habits, homework support, tutoring resources, and parent guidance for working with schools."],
      ["STEM & Technology", "Science, engineering, coding, AI literacy, digital creativity, online safety, and responsible technology use."],
      ["Discovering Gifts", "Activities and reflection that help children notice strengths, interests, creativity, practical abilities, and areas worth developing."],
      ["Money & Entrepreneurship", "Age-appropriate saving, budgeting, honest work, entrepreneurship, creating value, and understanding how money works."],
      ["Creativity & Arts", "Music, drawing, design, writing, video, photography, crafts, performance, and other creative outlets."],
      ["Career & Opportunity", "Youth programs, mentoring, career exposure, scholarships, competitions, camps, and other opportunities as they are verified."],
    ],
    scriptureSeries: [
      ["Wisdom & Understanding", ["Proverbs 4:7", "Proverbs 2:6", "James 1:5"], "Study wisdom, knowledge, understanding, and seeking direction."],
      ["Teaching Children", ["Deuteronomy 6:6-7", "Proverbs 22:6", "2 Timothy 3:15"], "Study intentional instruction, repetition, example, and learning from childhood."],
      ["Gifts, Skill & Diligence", ["1 Peter 4:10", "Exodus 35:30-35", "Proverbs 22:29"], "Study gifts, craftsmanship, skill development, service, and diligent work."],
    ],
  },
  {
    slug: "food-wellness",
    title: "Food & Family Wellness",
    shortTitle: "Food & Wellness",
    tag: "Nourish • Plan • Learn",
    summary: "Practical information for meal planning, cooking, grocery stewardship, healthy household habits, food resources, and children learning kitchen skills.",
    childFocus: "Teach children age-appropriate cooking, food knowledge, hygiene, planning, and responsibility around meals.",
    familyFocus: "Help families organize meals, stretch groceries, reduce waste, build routines, and locate credible food and wellness resources.",
    topics: [
      ["Meal Planning", "Weekly planning, family meals, preparation routines, use-first decisions, and reducing last-minute food stress."],
      ["Budget Grocery Skills", "Planning before shopping, comparing needs, using what is already available, and organizing purchases after the trip."],
      ["Cooking Skills", "Age-appropriate kitchen skills, recipes, food preparation, cleanup, safety, and children participating responsibly."],
      ["Food Storage & Inventory", "Simple systems for knowing what is on hand, what should be used first, what is running low, and what should not be repurchased."],
      ["Healthy Household Habits", "General wellness education, sleep and routine basics, movement, hygiene, hydration, and links to qualified health sources where needed."],
      ["Food Assistance", "Verified food pantries, school meal resources, benefit information, and community programs without charging families for basic access information."],
    ],
    scriptureSeries: [
      ["Provision & Preparation", ["Proverbs 31:14-15", "Proverbs 6:6-8", "1 Timothy 5:8"], "Study preparation, provision, responsibility, and caring for household needs."],
      ["Stewardship", ["John 6:12", "Luke 16:10", "Proverbs 21:20"], "Study avoiding waste, managing resources faithfully, and planning with what is available."],
      ["Care for the Body", ["1 Corinthians 6:19-20", "3 John 1:2", "1 Timothy 4:8"], "Study bodily stewardship while separating biblical principles from professional medical advice."],
    ],
  },
  {
    slug: "practical-life-skills",
    title: "Practical Life Skills",
    shortTitle: "Life Skills",
    tag: "Practice • Build • Become Capable",
    summary: "Useful skills children and families can practice for greater independence, confidence, creativity, responsibility, and future opportunity.",
    childFocus: "Help children build practical competence instead of reaching adulthood without experience in everyday responsibilities.",
    familyFocus: "Give parents a structured way to introduce life skills gradually, safely, and according to age and readiness.",
    topics: [
      ["Cooking & Kitchen", "Preparing food, cleaning as you go, understanding basic kitchen tools, safety, and serving the household."],
      ["Sewing & Clothing Care", "Beginner sewing, mending, measurements, garment care, creative construction, and responsible progression from learner to skilled maker."],
      ["Home Care", "Cleaning, laundry, organization, basic maintenance awareness, household standards, and learning how to care for shared spaces."],
      ["Money & Work", "Budgeting, saving, planning, work habits, entrepreneurship, customer service, and creating lawful value."],
      ["Technology & Media", "Digital literacy, AI literacy, editing, productivity tools, online safety, creative media, and responsible device use."],
      ["Creative & Practical Gifts", "Hair care, gardening, art, music, design, making, building, and other skills that can grow from interest into capability."],
    ],
    scriptureSeries: [
      ["Work & Diligence", ["Ecclesiastes 9:10", "Proverbs 22:29", "Colossians 3:23"], "Study wholehearted work, skill, excellence, and responsibility."],
      ["Craftsmanship", ["Exodus 31:1-5", "Exodus 35:30-35", "Proverbs 31:19"], "Study examples of craftsmanship, making, design, and skilled hands."],
      ["Responsibility & Growth", ["Luke 16:10", "Proverbs 13:4", "Galatians 6:5"], "Study faithfulness, responsibility, diligence, and gradual maturity."],
    ],
  },
  {
    slug: "household-management",
    title: "Home & Household Management",
    shortTitle: "Household Management",
    tag: "Order • Responsibility • Stewardship",
    summary: "Planning, routines, organization, household responsibilities, family scheduling, meal systems, inventory, and repeatable home procedures.",
    childFocus: "Teach children that a household works through shared responsibility, age-appropriate participation, consistency, and care for common spaces.",
    familyFocus: "Help parents reduce mental overload by turning repeated household work into visible routines, checklists, plans, and systems.",
    topics: [
      ["Morning & Evening Routines", "Simple repeatable routines for hygiene, rooms, school preparation, prayer, household resets, and bedtime preparation."],
      ["Children's Responsibilities", "Age-appropriate chores, responsibility rotation, clear expectations, verification, repair, and non-physical accountability systems."],
      ["Cleaning & Resets", "Daily resets, weekly cleaning, room standards, shared-space care, and procedures that are easier to repeat than to remember."],
      ["Family Scheduling", "Coordinating school, work, appointments, preparation, recurring responsibilities, and important family rhythms."],
      ["Meal & Inventory Systems", "Connecting meals, grocery planning, household inventory, use-first decisions, and preparation into one operating rhythm."],
      ["Household SOPs", "Step-by-step instructions for recurring tasks so adults and children can learn, follow, improve, and reuse a process."],
    ],
    scriptureSeries: [
      ["Building the Home", ["Proverbs 24:3-4", "Psalm 127:1", "Proverbs 14:1"], "Study wisdom, understanding, and what it means to build a household carefully."],
      ["Household Stewardship", ["Proverbs 31:27", "Luke 16:10", "1 Timothy 5:8"], "Study watching over household needs, faithful stewardship, and responsibility."],
      ["Order & Planning", ["1 Corinthians 14:40", "Proverbs 21:5", "Proverbs 16:3"], "Study order, diligent planning, and committing work to God."],
    ],
  },
  {
    slug: "family-stability",
    title: "Family Stability & Support",
    shortTitle: "Family Stability",
    tag: "Stabilize • Strengthen • Move Forward",
    summary: "A practical information hub for the pressures that affect family stability, including housing, transportation, finances, employment, routines, parenting, and access to qualified support.",
    childFocus: "Keep the child's safety, development, learning, routine, and future opportunities visible when a household is under pressure.",
    familyFocus: "Help families understand options, organize next steps, and reach qualified services without presenting Hands Gifted as a lawyer, clinician, social worker, or government agency.",
    topics: [
      ["Housing Stability", "Rental resources, eviction-prevention information, utility support, document readiness, affordable-housing resources, and homeownership education."],
      ["Transportation", "Public transit, family transportation planning, youth transportation questions, employment transportation, and verified local assistance programs."],
      ["Employment & Workforce", "Job-search resources, training, workforce programs, resume readiness, scheduling, and pathways toward more stable earned income."],
      ["Family Money", "Budget organization, prioritizing necessities, financial literacy, benefit-navigation information, saving, and longer-term stability planning."],
      ["Parenting & Family Routines", "Children's needs, consistent routines, communication, school support, household expectations, family goals, and finding professional help when appropriate."],
      ["Culturally Relevant Resource Research", "Reliable information about barriers and opportunities affecting Black, Hispanic, and Native American families, presented with evidence and without assuming every family has the same experience."],
    ],
    scriptureSeries: [
      ["Foundation & Direction", ["Joshua 24:15", "Psalm 127:1", "Proverbs 3:5-6"], "Study household direction, dependence on God, and building with purpose."],
      ["Planning & Provision", ["Proverbs 21:5", "Luke 14:28", "1 Timothy 5:8"], "Study planning, counting costs, provision, and responsibility."],
      ["Perseverance & Help", ["Galatians 6:2", "Ecclesiastes 4:9-10", "Isaiah 41:10"], "Study mutual support, perseverance, and seeking help rather than carrying every burden alone."],
    ],
  },
  {
    slug: "community-resources",
    title: "Community Resources & Opportunities",
    shortTitle: "Community Resources",
    tag: "Find Help • Find Opportunity • Verify First",
    summary: "A growing directory of trustworthy programs, public resources, youth opportunities, family assistance, and community organizations.",
    childFocus: "Connect children and youth with safe, age-appropriate learning, enrichment, mentoring, creative, career, and development opportunities.",
    familyFocus: "Make it easier for parents to find and compare assistance, eligibility, contact details, service areas, costs, transportation information, and last-verified dates.",
    topics: [
      ["Youth Programs", "After-school programs, mentoring, music, STEM, leadership, entrepreneurship, arts, camps, and other verified opportunities."],
      ["School & Back-to-School", "School-supply drives, clothing resources, academic support, tutoring, school-meal information, and seasonal programs."],
      ["Food, Housing & Utilities", "Community organizations and public programs that address essential family needs."],
      ["Childcare & Transportation", "Childcare resources, youth pickup/transport questions, public transportation, and assistance programs as available."],
      ["Workforce & Business", "Workforce programs, training, small-business development, entrepreneurship resources, and legitimate funding or technical-assistance opportunities."],
      ["Women's & Family Support", "Programs for women, parents, caregivers, families, family education, safety, and practical support from qualified organizations."],
    ],
    scriptureSeries: [
      ["Serving Others", ["Galatians 6:2", "Philippians 2:4", "Hebrews 13:16"], "Study bearing burdens, considering the needs of others, and doing good."],
      ["Generosity & Mercy", ["Proverbs 19:17", "Deuteronomy 15:7-8", "James 2:15-16"], "Study practical care for people facing material need."],
      ["Wise Counsel & Verification", ["Proverbs 11:14", "Proverbs 18:13", "1 Thessalonians 5:21"], "Study counsel, listening before answering, testing information, and holding to what is sound."],
    ],
  },
] as const;

export function getPublicResourceArea(slug: string) {
  return publicResourceAreas.find((area) => area.slug === slug);
}
