import type { Metadata } from "next";
import { CommandCenterShell } from "../_components/CommandCenterShell";
import styles from "../command-center.module.css";

export const metadata:Metadata={title:"Command Center Design Preview",robots:{index:false,follow:false}};
const items=[
 {reason:"High priority · due soon",title:"Review a website-development decision",meta:"business · review · today",action:"Review",tone:"attention"},
 {reason:"Parent verification",title:"One household responsibility needs a check",meta:"family · verification",action:"Verify",tone:"scheduled"},
 {reason:"Follow-up date reached",title:"Follow up on an outside response",meta:"business · waiting",action:"Follow up",tone:"neutral"},
 {reason:"Learning follow-up",title:"Review a Family Academy item",meta:"family · learning",action:"Review",tone:"scheduled"},
] as const;
export default function DesignPreviewPage(){return <CommandCenterShell active="today" context="all" rightRail={<><div className={styles.detailCard}><h3>Design preview</h3><p>This page uses synthetic records only. No private family or business data is shown.</p></div><div className={styles.detailCard} style={{marginTop:10}}><h3>Operating rule</h3><p>The real Command Center will surface live authorized records through Supabase RLS after the design is approved.</p></div></>}>
 <section className={styles.commandStrip}><div><div className={styles.eyebrow}>Thursday, Sep 17</div><h1>What needs my attention now?</h1><p>1 critical · 2 decisions · 3 follow-ups</p></div><a className={styles.focusButton} href="#capture-preview">Capture</a></section>
 <div className={styles.metrics}><div className={styles.metric}><strong>1</strong><span>Critical</span></div><div className={styles.metric}><strong>4</strong><span>Due / review</span></div><div className={styles.metric}><strong>2</strong><span>Decisions</span></div><div className={styles.metric}><strong>3</strong><span>Waiting</span></div></div>
 <section className={styles.section}><div className={styles.sectionHeader}><h2>Attention stack</h2><a href="#attention">View all</a></div>{items.map((item,index)=><div className={styles.row} key={item.title}><span className={`${styles.severity} ${styles[item.tone]}`}/><div className={styles.rowMain}><div className={styles.rowReason}>{item.reason}</div><div className={styles.rowTitle}>{item.title}</div><div className={styles.rowMeta}><span>{item.meta}</span></div></div><button className={styles.primaryAction}>{item.action}</button></div>)}</section>
 <section className={styles.section}><div className={styles.sectionHeader}><h2>Decisions</h2><a href="#decisions">Open approvals</a></div><div className={styles.summaryGrid}><div className={styles.summaryCard}><strong>1</strong><span>Content review</span><p>Approve, revise, or keep private.</p></div><div className={styles.summaryCard}><strong>1</strong><span>Parent check</span><p>Verify completion or request correction.</p></div><div className={styles.summaryCard}><strong>3</strong><span>Projects</span><p>Projects needing a clear next action.</p></div></div></section>
 <section className={styles.section}><div className={styles.sectionHeader}><h2>Today timeline</h2><a href="#calendar">Calendar</a></div><div className={styles.timeline}><div className={styles.timelineItem}><div className={styles.time}>10:00 AM</div><div><strong>Business follow-up</strong><span>Call / confirm next step</span></div></div><div className={styles.timelineItem}><div className={styles.time}>3:30 PM</div><div><strong>Family check-in</strong><span>Review today’s household needs</span></div></div></div></section>
 <section className={styles.section}><div className={styles.sectionHeader}><h2>Waiting & blockers</h2><a href="#waiting">View all</a></div><div className={styles.row}><span className={`${styles.severity} ${styles.neutral}`}/><div className={styles.rowMain}><div className={styles.rowReason}>Waiting</div><div className={styles.rowTitle}>External response needed before next step</div><div className={styles.rowMeta}><span>Follow up today</span></div></div><button className={`${styles.primaryAction} ${styles.secondaryAction}`}>Follow up</button></div></section>
 <section className={styles.section}><div className={styles.sectionHeader}><h2>Close the day</h2><a href="#weekly">Weekly review</a></div><div className={styles.empty}>Clear urgent work, update waiting items, and leave every unfinished item with one clear next action.</div></section>
 </CommandCenterShell>}
